from .string_enum import StringEnum
from enum import auto


class Occasion(StringEnum):
    ANNIVERSARY = auto()
    BAPTISM = auto()
    BAR_OR_BAT_MITZVAH = auto()
    BIRTHDAY = auto()
    CANADA_DAY = auto()
    CHINESE_NEW_YEAR = auto()
    CINCO_DE_MAYO = auto()
    CONFIRMATION = auto()
    CHRISTMAS = auto()
    DAY_OF_THE_DEAD = auto()
    EASTER = auto()
    EID = auto()
    ENGAGEMENT = auto()
    FATHERS_DAY = auto()
    GET_WELL = auto()
    GRADUATION = auto()
    HALLOWEEN = auto()
    HANUKKAH = auto()
    HOUSEWARMING = auto()
    KWANZAA = auto()
    PROM = auto()
    JULY_4TH = auto()
    MOTHERS_DAY = auto()
    NEW_BABY = auto()
    NEW_YEARS = auto()
    QUINCEANERA = auto()
    RETIREMENT = auto()
    ST_PATRICKS_DAY = auto()
    SWEET_16 = auto()
    SYMPATHY = auto()
    THANKSGIVING = auto()
    VALENTINES = auto()
    WEDDING = auto()
